### ISSUE TITLE
This browser or app may not be secure.

### ISSUE THREAD

**Issue by yash3001** [SHUR1K-N/MeetNinja-Google-Meet-Bot#10]
I am getting the following error

```
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

**Comment by SHUR1K-N** [comment]
This issue had already been raised and closed, you may check [this Issue thread](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/5) out.

**TL;DR:** Google has trust issues, G-Suite e-mail addresses are fine, but regular e-mail addresses may face this issue. Try getting Google "accustomed" to your device/IP by multiple successful sign-ins to see if Google bestows upon your device/IP its trust.
