### ISSUE TITLE
Running on Linux gives "SyntaxError: Non-ASCII character '\xe2' in file MeetNinja.py on line 54, but no encoding declared"

### ISSUE THREAD

**Issue by T4R1Q05** [SHUR1K-N/MeetNinja-Google-Meet-Bot#15]
SyntaxError: Non-ASCII character '\xe2' in file MeetNinja.py on line 54, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

any solution for this?

**Comment by SHUR1K-N** [comment]
Have you PIP-installed the packages "colorama" and "termcolor" before running MeetNinja?

**Comment by T4R1Q05** [comment]
> Have you PIP-installed the packages "colorama" and "termcolor" before running MeetNinja?

Nope sorry, I just followed the instructions where it says pip install -r requirements.txt
just ran pip install colorama and it said Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (0.4.3)
and the same this with termcolor

**Comment by SHUR1K-N** [comment]
Alright, found the culprit!

You are now running MeetNinja as:
`python MeetNinja.py`

Try running it as:
`python3 MeetNinja.py`

This will resolve the issue you are facing.

**Comment by T4R1Q05** [comment]
> Alright, found the culprit!
> 
> You are now running MeetNinja as:
> `python MeetNinja.py`
> 
> Try running it as:
> `python3 MeetNinja.py`
> 
> This will resolve the issue you are facing.

executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(executable_path=BROWSER_DRIVER, options=firefoxOptions)
 Failed!
the path I used was from your list for 32 bit Linux

**Comment by SHUR1K-N** [comment]
*Are* you in fact running a 32-bit Linux operating system?

**Comment by T4R1Q05** [comment]
> _Are_ you in fact running a 32-bit Linux operating system?

yes
ran uname -m and got I686 which is 32bit linux

**Comment by SHUR1K-N** [comment]
What matters is, does MeetNinja open a Firefox window after it? If yes, you can ignore the deprecation warning.

**Comment by T4R1Q05** [comment]
> What matters is, does MeetNinja open a Firefox window after it? If yes, you can ignore the deprecation warning.

nope it does not open firefox
BROWSER_DRIVER = "FirefoxDrivers/linux32/geckodriver"

**Comment by SHUR1K-N** [comment]
Alright, a fix for this will be up within 30 minutes!

**Comment by SHUR1K-N** [comment]
Done! You can download the latest version of MeetNinja and report back.

If you face an issue, you may open another Issue with the relevant subject (for organizational/search purposes) since the initial "SyntaxError" issue was technically resolved in this thread.
