### ISSUE TITLE
Running on Linux gives "TypeError: init() got an unexpected keyword argument 'service'"

### ISSUE THREAD

**Issue by T4R1Q05** [SHUR1K-N/MeetNinja-Google-Meet-Bot#17]
After removing the hash from line 279 leaving me with 
line 281
    genericError()
                 ^
IndentationError: unindent does not match any outer indentation level

**Comment by SHUR1K-N** [comment]
Could you share a screenshot of the code of the last few lines? There seems to be a minor indentation error from your editing.

**Comment by T4R1Q05** [comment]
![Capture](https://user-images.githubusercontent.com/77877840/105680662-f53ffd80-5ee7-11eb-9fe9-74a08a6bf0db.PNG)
![Capture](https://user-images.githubusercontent.com/77877840/105680862-43550100-5ee8-11eb-9119-c4ec93d44d07.PNG)

**Comment by T4R1Q05** [comment]
> Could you share a screenshot of the code of the last few lines? There seems to be a minor indentation error from your editing.

![image](https://user-images.githubusercontent.com/77877840/105680939-5a93ee80-5ee8-11eb-9515-8b5078c2d8a0.png)

**Comment by SHUR1K-N** [comment]
You have an unwanted space before `print(e)`. Spaces/Indentations are crucial in Python, remove the single space character and share he traceback generated upon re-running.

**Comment by T4R1Q05** [comment]
> You have an unwanted space before `print(e)`. Spaces/Indentations are crucial in Python, remove the single space character and share he traceback generated upon re-running.

line 247, in <module>
    driver = initBrowser()
  File "main.py", line 141, in initBrowser
    driver = webdriver.Firefox(service=serv, options=firefoxOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 279, in <module>
    print(e)
NameError: name 'e' is not defined

**Comment by SHUR1K-N** [comment]
When you "re-installed" MeetNinja, did you just re-download the MeetNinja.py file? Or had you used "git clone" again or re-downloaded the complete repository along with the ChromeDrivers / FirefoxDrivers folders?

**Comment by T4R1Q05** [comment]
> When you "re-installed" MeetNinja, did you just re-download the MeetNinja.py file? Or had you used "git clone" again or re-downloaded the complete repository along with the ChromeDrivers / FirefoxDrivers folders?

I rm -rf the file and the git cloned the link and did the requirements and I did nothing with the Firefox Drivers

**Comment by SHUR1K-N** [comment]
Perfect. However, since the Firefox browser drivers were updated in the latest version of MeetNinja, could you check what version the Firefox browser is running on for you? (Hamburger menu > Help > About Firefox)

**Comment by T4R1Q05** [comment]
> Perfect. However, since the Firefox browser drivers were updated in the latest version of MeetNinja, could you check what version the Firefox browser is running on for you? (Hamburger menu > Help > About Firefox)

![image](https://user-images.githubusercontent.com/77877840/105683516-9d0afa80-5eeb-11eb-851b-5f4d698ce277.png)

**Comment by SHUR1K-N** [comment]
You seem to be on an ESR version (the default version that comes with a Linux distribution). You may remove the ESR version using:

`sudo apt-get remove firefox-esr`

And then, you may install the latest release version of Firefox using:

`sudo apt install firefox`

**Comment by T4R1Q05** [comment]
> You seem to be on an ESR version (the default version that comes with a Linux distribution). You may remove the ESR version using:
> 
> `sudo apt-get remove firefox-esr`
> 
> And then, you may install the latest release version of Firefox using:
> 
> `sudo apt install firefox`

![image](https://user-images.githubusercontent.com/77877840/105688753-e0686780-5ef1-11eb-85f0-3f40321583a9.png)
I think I broke it

**Comment by SHUR1K-N** [comment]
No worries, you may follow the "Alternative way to install Firefox" section in [this guide](https://miloserdov.org/?p=2848).

**Comment by SHUR1K-N** [comment]
Was your problem solved? If so, you may close an opened Issue so it may help other users and optimize organization.

**Comment by T4R1Q05** [comment]
First time I've broken it, it says I have no space left even though I have given it 10GB with nothing installed on it.

**Comment by SHUR1K-N** [comment]
Did you follow the instructions in the guide I had posted earlier? I followed it myself just to confirm and it worked just fine.

**Comment by T4R1Q05** [comment]
> Did you follow the instructions in the guide I had posted earlier? I followed it myself just to confirm and it worked just fine.

I think it's because the installation is for 64bit
![image](https://user-images.githubusercontent.com/77877840/105720851-d196aa80-5f1b-11eb-92cb-3c888239ae61.png)

**Comment by SHUR1K-N** [comment]
Instead of executing the first command `wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"` which is for 64-bit Linux systems, run this instead for a 32-bit Linux system:

`wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux&lang=en-US"`

**Comment by T4R1Q05** [comment]
> Instead of executing the first command `wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"` which is for 64-bit Linux systems, run this instead for a 32-bit Linux system:
> 
> `wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux&lang=en-US"`

I don't know what has happened but every time I try to log in it just sends me back to the login screen

**Comment by SHUR1K-N** [comment]
Are you referring to the Linux login screen?

**Comment by T4R1Q05** [comment]
yep

**Comment by SHUR1K-N** [comment]
This issue is completely unrelated to MeetNinja, and as I am not primarily a Linux user (I just use it to test my code), I am afraid I will not be able to help you. Do Google around and I am sure you will find a solution to this problem. You may re-open or open a fresh Issue here with the relevant subject regarding any MeetNinja issue and I will be happy to help!
