### ISSUE TITLE
Can't run because there is no module named pause

### ISSUE THREAD

**Issue by ghost** [SHUR1K-N/MeetNinja-Google-Meet-Bot#22]
Traceback (most recent call last):
  File "/home/kali/MeetNinja-Google-Meet-Bot/MeetNinja.py", line 9, in <module>
    import pause; import os; import re
ModuleNotFoundError: No module named 'pause'
I'm on linux, i'm using python3 and edited the credentials and everything but can't run it

**Comment by SHUR1K-N** [comment]
You do not have the required package(s) installed to be running MeetNinja. Kindly, refer to point `#1.2.` from within the "Possible fixes" message when MeetNinja fails for you. It says:

"1.2. Make sure you have pip-installed all the required python packages mentioned in the README"

**Comment by ghost** [comment]
sorry comrade, thought i had everything installed

**Comment by SHUR1K-N** [comment]
No worries, comrade; happens with even the best of us!
