### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by reeswar21** [SHUR1K-N/MeetNinja-Google-Meet-Bot#28]
May I know what version does the chrome driver support? I suppose there's something wrong with chrome 

And also should i replace this with another chromedriver version?
<img width="140" alt="Screenshot 2021-05-12 at 5 20 11 PM" src="https://user-images.githubusercontent.com/75256095/117951001-516b4800-b346-11eb-98af-30f7c64056e0.png">

**Comment by SHUR1K-N** [comment]
> May I know what version does the chrome driver support?

Example: If your installation of Google Chrome is running on, say, version 90, then you should download chromedriver version 90 as well.

> And also should i replace this with another chromedriver version?

Yes.

**Comment by reeswar21** [comment]
<img width="418" alt="Screenshot 2021-05-12 at 5 23 38 PM" src="https://user-images.githubusercontent.com/75256095/117951536-d6eef800-b346-11eb-9795-afe1a9fe2229.png">

Which chromedriver should i download for this version

**Comment by SHUR1K-N** [comment]
> > May I know what version does the chrome driver support?
> 
> Example: If your installation of Google Chrome is running on, say, version 90, then you should download chromedriver version 90 as well.
> 
> > And also should i replace this with another chromedriver version?
> 
> Yes.

Your question regarding the version to download has been answered here.

**Comment by reeswar21** [comment]
What do I do now? I have done all the steps until
<img width="567" alt="Screenshot 2021-05-12 at 5 30 53 PM" src="https://user-images.githubusercontent.com/75256095/117952516-d014b500-b347-11eb-823b-c66f1ddf1b89.png">
 now

**Comment by reeswar21** [comment]
Can I have your number please and also I have already posted on the web
related to the issue

**Comment by SHUR1K-N** [comment]
As stated previously (quite a few times, actually), you will need to provide proper _permissions_ to the MeetNinja directory's content using `chmod` successfully in order for you to be able to _run_ it.

> Can I have your number please 

Sorry, no. This is not an Issue related to MeetNinja whatsoever; it seems to be a machine-specific problem on your end. I am afraid I would not be able to assist you any further until you figure the permissions anomaly out and _then_ see if MeetNinja does not work for you.
