### ISSUE TITLE
What's the next step

### ISSUE THREAD

**Issue by reeswar21** [SHUR1K-N/MeetNinja-Google-Meet-Bot#29]
<img width="574" alt="Screenshot 2021-05-12 at 5 34 46 PM" src="https://user-images.githubusercontent.com/75256095/117953055-5a5d1900-b348-11eb-89cc-7013f7a6cd87.png">

**Comment by SHUR1K-N** [comment]
You cannot keep opening new Issues for the same issue without reading any of my comments thoroughly and trying the solutions I have been suggesting for multiple comments consecutively... This is not the protocol.
