### ISSUE TITLE
web browser not secure

### ISSUE THREAD

**Issue by Clogheadcodm** [SHUR1K-N/MeetNinja-Google-Meet-Bot#31]
heyy,i have already read the previous threads regarding this issue and tried everything including diabling two step verification,switching on java script and allowing less secure stuff to run, but it still doesnt work,wud appreciate if u cud help.
Cheers!!

https://user-images.githubusercontent.com/85901002/122007203-530cad80-cdd5-11eb-90ee-7aa2693cad52.mp4

**Comment by SHUR1K-N** [comment]
Thank you for the video, it helps creators / developers much more when you supplement media with your Issue!

Regarding the problem at hand, this has already been discussed in previously closed Issues, [here](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/10) and [here](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/5). Spoiler alert though, this may unfortunately not work with many regular Gmail e-mail addresses, but most G-Suite e-mail addresses (organization-provided Gmail addresses) should work just as intended.

**Comment by Clogheadcodm** [comment]
is there a link between this issue and this video,wud it help? Check it out

https://www.youtube.com/watch?v=FVumnHy5Tzo
