### ISSUE TITLE
error in README.md file 

### ISSUE THREAD

**Issue by shivendradb** [SHUR1K-N/MeetNinja-Google-Meet-Bot#32]
There is an error in the Readme file.
Under the "Usage" section, in the 2nd point, the spelling of requirements is wrong on "pip install -r requirments.txt" sentence.
Kindly update the above issue.
Thank you

Note: Screenshot is attached for the reference.

![image](https://user-images.githubusercontent.com/62358100/124389400-7a83d580-dd04-11eb-9c80-1ae0e7fee350.png)

**Comment by SHUR1K-N** [comment]
This has been fixed. Cheers, comrade!
