### ISSUE TITLE
init() got an unexpected keyword argument 'service'

### ISSUE THREAD

**Issue by reeswar21** [SHUR1K-N/MeetNinja-Google-Meet-Bot#33]
Python 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
===== RESTART: /Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py ====
[34m
   ███▄ ▄███▓▓█████ ▓█████▄▄▄█████▓ ███▄    █  ██▓ ███▄    █  ▄▄▄██▀▀▀▄▄▄
  ▓██▒▀█▀ ██▒▓█   ▀ ▓█   ▀▓  ██▒ ▓▒ ██ ▀█   █ ▓██▒ ██ ▀█   █    ▒██  ▒████▄
  ▓██    ▓██░▒███   ▒███  ▒ ▓██░ ▒░▓██  ▀█ ██▒▒██▒▓██  ▀█ ██▒   ░██  ▒██  ▀█▄
  ▒██    ▒██ ▒▓█  ▄ ▒▓█  ▄░ ▓██▓ ░ ▓██▒  ▐▌██▒░██░▓██▒  ▐▌██▒▓██▄██▓ ░██▄▄▄▄██
  ▒██▒   ░██▒░▒████▒░▒████▒ ▒██▒ ░ ▒██░   ▓██░░██░▒██░   ▓██░ ▓███▒   ▓█   ▓██▒
  ░ ▒░   ░  ░░░ ▒░ ░░░ ▒░ ░ ▒ ░░   ░ ▒░   ▒ ▒ ░▓  ░ ▒░   ▒ ▒  ▒▓▒▒░   ▒▒   ▓▒█░
  ░  ░      ░ ░ ░  ░ ░ ░  ░   ░    ░ ░░   ░ ▒░ ▒ ░░ ░░   ░ ▒░ ▒ ░▒░    ▒   ▒▒ ░
  ░      ░      ░      ░    ░         ░   ░ ░  ▒ ░   ░   ░ ░  ░ ░ ░    ░   ▒
         ░      ░  ░   ░  ░                 ░  ░           ░  ░   ░        ░  ░[0m
[34m                    ------------------------------------[0m
[31m                    || MeetNinja: The Google Meet Bot ||[0m
[34m                    ------------------------------------[0m

Checking for MeetNinja updates...[32m You are using the latest version!
[0m

Initializing browser...Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 235, in <module>
    driver = initBrowser()
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 114, in initBrowser
    driver = webdriver.Chrome(service=servicePath, options=chromeOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 267, in <module>
    print(e)
NameError: name 'e' is not defined
>>>

**Comment by reeswar21** [comment]
I checked the related issues to this and i also changed python to 3.8.6 but it still has this TypeError: init() got an unexpected keyword argument 'service'
Please help me!

**Comment by SHUR1K-N** [comment]
This is a duplicate Issue. You may check the following closed Issues for a possible solution:

1. https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/17
2. https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/18

**Comment by reeswar21** [comment]
I have solved this issue but I can't use my own Gmail because it says the browser is not secure but I can use my school email to access it and it runs perfectly!

**Comment by SHUR1K-N** [comment]
This is also a duplicate Issue. You may check the following closed Issue for the quick explanation of why this happens:

- https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/10
