### ISSUE TITLE
Firefox doesn't end the meeting

### ISSUE THREAD

**Issue by anjannair** [SHUR1K-N/MeetNinja-Google-Meet-Bot#4]
Error is shown instead of ending the meeting. For Chrome it works properly. Check the code.

**Comment by SHUR1K-N** [comment]
Meets end perfectly on my end, tested on multiple devices. Could you add "print(e)" as the first line of the general/last exception handling block on your end and let me kmow what the culprit is? Thanks.

**Comment by anjannair** [comment]
Just add a print(e)?

**Comment by SHUR1K-N** [comment]
Yes, and execute. We need to see the exception instead of the exception handling "possible fixes" message in the MeetNinja console window. Also, were you able to reproduce this issue multiple times? Or was it just a single occurrence?

**Comment by SHUR1K-N** [comment]
**[Closed]** Reason: Lack of follow-up/response. Do open/re-open if or when you are able to reproduce this issue.
