### ISSUE TITLE
No audio in Meet, shows speakers are blocked in Settings

### ISSUE THREAD

**Issue by dproyt** [SHUR1K-N/MeetNinja-Google-Meet-Bot#7]
ACTUALLY I CANT HEAR ANYTHING IN MEET WHEN I GO TO SETTINGS IT SHOWS SPEAKERS ARE BLOCKED

**Comment by SHUR1K-N** [comment]
There is no code in MeetNinja that blocks audio output. Only the camera and _microphone_ are blocked. Can you share a screenshot that displays the audio output as blocked?

**Comment by dproyt** [comment]
![Capture](https://user-images.githubusercontent.com/74549153/99356693-913dff00-28d0-11eb-9b11-823568e7fcd3.PNG)

**Comment by SHUR1K-N** [comment]
Tested across multiple devices at my end — no such issue. As mentioned earlier, there _is_ no code in MeetNinja that can cause this. This is probably an issue at your end; try to see if you have sufficient audio permissions provided to applications, etc..

**Comment by dproyt** [comment]
BRO NOW ONE POP UP COMES FOR MIC AND CAM BLOCKED AND BOT FAILS TO PRESS THE DISMISS BUTTON

**Comment by SHUR1K-N** [comment]
You may open a separate Issue thread for this specific issue.
