### ISSUE TITLE
Pop-up blocks "Join" button

### ISSUE THREAD

**Issue by dproyt** [SHUR1K-N/MeetNinja-Google-Meet-Bot#9]
WHEN WE GO TO MEET PAGE IT BLOCKS MIC AND CAM THEN IT SHOWS THE POPUP WHICH IS TO BE DISMISSED THAT POPUP BLOCKS JOIN MEET BUTTON

**Comment by SHUR1K-N** [comment]
Tested across multiple devices at my end — no such issue.

There is a specific line in MeetNinja ([line #159](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/blob/24b92d39c9072c963cfdefe8f039216c31702f1d/MeetNinja.py#L159)), `action.send_keys(Keys.ESCAPE).perform()`, that _specifically_ deals with this exact "Dismiss" button by simulating an "Esc" key-press to kill the pop-up.

So, this should not be an issue unless you have either:
- Explicitly Minimized the web browser window (which blocks clicks), or
- Made some other change(s) in the code (such as decreasing or removing `time.sleep()` values) that I would not be aware of unless shared

**Comment by dproyt** [comment]
I FIXEEDDD ITTT I MADE IT FULL SCREEN
